import 'package:flame_game/model/card_model.dart';
import 'package:flame_game/model/enums.dart';

class CardData {
  // 開發團隊角色
  static List<CardModel> createDeveloperCards() {
    return [
      CardModel.createProgrammerCard(
        name: '前端工程師',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 80,
        mpAdd: 120,
        pointAdd: 100,
        createAdd: 60,
        popularAdd: 40,
      ),
      CardModel.createProgrammerCard(
        name: '後端工程師',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 90,
        mpAdd: 110,
        pointAdd: 100,
        createAdd: 50,
        popularAdd: 30,
      ),
      CardModel.createProgrammerCard(
        name: '全端工程師',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 100,
        mpAdd: 130,
        pointAdd: 120,
        createAdd: 70,
        popularAdd: 50,
      ),
      CardModel.createProgrammerCard(
        name: '資安工程師',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 95,
        mpAdd: 125,
        pointAdd: 110,
        createAdd: 65,
        popularAdd: 45,
      ),
      CardModel.createProgrammerCard(
        name: '測試工程師',
        rank: CardRank.R,
        connect: 3,
        hpAdd: 75,
        mpAdd: 115,
        pointAdd: 90,
        createAdd: 55,
        popularAdd: 35,
      ),
      CardModel.createProgrammerCard(
        name: 'DevOps工程師',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 105,
        mpAdd: 135,
        pointAdd: 130,
        createAdd: 75,
        popularAdd: 55,
      ),
      CardModel.createProgrammerCard(
        name: '資料工程師',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 85,
        mpAdd: 125,
        pointAdd: 105,
        createAdd: 65,
        popularAdd: 45,
      ),
      CardModel.createProgrammerCard(
        name: '演算法工程師',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 110,
        mpAdd: 140,
        pointAdd: 140,
        createAdd: 80,
        popularAdd: 60,
      ),
      CardModel.createProgrammerCard(
        name: '遊戲工程師',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 115,
        mpAdd: 145,
        pointAdd: 150,
        createAdd: 85,
        popularAdd: 65,
      ),
      CardModel.createProgrammerCard(
        name: '嵌入式工程師',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 85,
        mpAdd: 125,
        pointAdd: 105,
        createAdd: 65,
        popularAdd: 45,
      ),
    ];
  }

  // 設計團隊角色
  static List<CardModel> createDesignerCards() {
    return [
      CardModel.createDesignerCard(
        name: 'UI設計師',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 70,
        mpAdd: 110,
        pointAdd: 90,
        createAdd: 80,
        popularAdd: 50,
      ),
      CardModel.createDesignerCard(
        name: 'UX設計師',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 75,
        mpAdd: 115,
        pointAdd: 95,
        createAdd: 85,
        popularAdd: 55,
      ),
      CardModel.createDesignerCard(
        name: '視覺設計師',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 80,
        mpAdd: 120,
        pointAdd: 100,
        createAdd: 90,
        popularAdd: 60,
      ),
      CardModel.createDesignerCard(
        name: '動畫設計師',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 85,
        mpAdd: 125,
        pointAdd: 105,
        createAdd: 95,
        popularAdd: 65,
      ),
      CardModel.createDesignerCard(
        name: '3D建模師',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 75,
        mpAdd: 115,
        pointAdd: 95,
        createAdd: 85,
        popularAdd: 55,
      ),
      CardModel.createDesignerCard(
        name: '遊戲美術師',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 90,
        mpAdd: 130,
        pointAdd: 110,
        createAdd: 100,
        popularAdd: 70,
      ),
      CardModel.createDesignerCard(
        name: '插畫師',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 70,
        mpAdd: 110,
        pointAdd: 90,
        createAdd: 80,
        popularAdd: 50,
      ),
      CardModel.createDesignerCard(
        name: '平面設計師',
        rank: CardRank.R,
        connect: 2,
        hpAdd: 65,
        mpAdd: 105,
        pointAdd: 85,
        createAdd: 75,
        popularAdd: 45,
      ),
      CardModel.createDesignerCard(
        name: '互動設計師',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 85,
        mpAdd: 125,
        pointAdd: 105,
        createAdd: 95,
        popularAdd: 65,
      ),
      CardModel.createDesignerCard(
        name: '品牌設計師',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 90,
        mpAdd: 130,
        pointAdd: 110,
        createAdd: 100,
        popularAdd: 70,
      ),
    ];
  }

  // 管理團隊角色
  static List<CardModel> createManagerCards() {
    return [
      CardModel.createManagerCard(
        name: '產品經理',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 80,
        mpAdd: 120,
        pointAdd: 100,
        createAdd: 60,
        popularAdd: 40,
      ),
      CardModel.createManagerCard(
        name: '專案經理',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 85,
        mpAdd: 125,
        pointAdd: 105,
        createAdd: 65,
        popularAdd: 45,
      ),
      CardModel.createManagerCard(
        name: '技術主管',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 90,
        mpAdd: 130,
        pointAdd: 110,
        createAdd: 70,
        popularAdd: 50,
      ),
      CardModel.createManagerCard(
        name: '產品總監',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 95,
        mpAdd: 135,
        pointAdd: 115,
        createAdd: 75,
        popularAdd: 55,
      ),
      CardModel.createManagerCard(
        name: '研發主管',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 90,
        mpAdd: 130,
        pointAdd: 110,
        createAdd: 70,
        popularAdd: 50,
      ),
      CardModel.createManagerCard(
        name: '營運主管',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 95,
        mpAdd: 135,
        pointAdd: 115,
        createAdd: 75,
        popularAdd: 55,
      ),
      CardModel.createManagerCard(
        name: '品質主管',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 80,
        mpAdd: 120,
        pointAdd: 100,
        createAdd: 60,
        popularAdd: 40,
      ),
      CardModel.createManagerCard(
        name: '敏捷教練',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 75,
        mpAdd: 115,
        pointAdd: 95,
        createAdd: 55,
        popularAdd: 35,
      ),
      CardModel.createManagerCard(
        name: '風險管理師',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 85,
        mpAdd: 125,
        pointAdd: 105,
        createAdd: 65,
        popularAdd: 45,
      ),
      CardModel.createManagerCard(
        name: '資源規劃師',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 80,
        mpAdd: 120,
        pointAdd: 100,
        createAdd: 60,
        popularAdd: 40,
      ),
    ];
  }

  // 行銷團隊角色
  static List<CardModel> createMarketerCards() {
    return [
      CardModel.createMarketerCard(
        name: '社群經理',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 75,
        mpAdd: 115,
        pointAdd: 95,
        createAdd: 55,
        popularAdd: 75,
      ),
      CardModel.createMarketerCard(
        name: '內容行銷師',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 70,
        mpAdd: 110,
        pointAdd: 90,
        createAdd: 60,
        popularAdd: 70,
      ),
      CardModel.createMarketerCard(
        name: 'SEO專家',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 80,
        mpAdd: 120,
        pointAdd: 100,
        createAdd: 65,
        popularAdd: 80,
      ),
      CardModel.createMarketerCard(
        name: '數位行銷師',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 85,
        mpAdd: 125,
        pointAdd: 105,
        createAdd: 70,
        popularAdd: 85,
      ),
      CardModel.createMarketerCard(
        name: '品牌經理',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 90,
        mpAdd: 130,
        pointAdd: 110,
        createAdd: 75,
        popularAdd: 90,
      ),
      CardModel.createMarketerCard(
        name: '公關經理',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 75,
        mpAdd: 115,
        pointAdd: 95,
        createAdd: 55,
        popularAdd: 75,
      ),
      CardModel.createMarketerCard(
        name: '活動企劃師',
        rank: CardRank.SR,
        connect: 3,
        hpAdd: 70,
        mpAdd: 110,
        pointAdd: 90,
        createAdd: 60,
        popularAdd: 70,
      ),
      CardModel.createMarketerCard(
        name: '市場分析師',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 80,
        mpAdd: 120,
        pointAdd: 100,
        createAdd: 65,
        popularAdd: 80,
      ),
      CardModel.createMarketerCard(
        name: '用戶增長專家',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 85,
        mpAdd: 125,
        pointAdd: 105,
        createAdd: 70,
        popularAdd: 85,
      ),
      CardModel.createMarketerCard(
        name: '社群小編',
        rank: CardRank.R,
        connect: 2,
        hpAdd: 65,
        mpAdd: 105,
        pointAdd: 85,
        createAdd: 50,
        popularAdd: 65,
      ),
    ];
  }

  // 特殊角色
  static List<CardModel> createSpecialCards() {
    return [
      CardModel.createProgrammerCard(
        name: '技術作家',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 85,
        mpAdd: 125,
        pointAdd: 105,
        createAdd: 75,
        popularAdd: 65,
      ),
      CardModel.createDesignerCard(
        name: '技術講師',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 90,
        mpAdd: 130,
        pointAdd: 110,
        createAdd: 80,
        popularAdd: 70,
      ),
      CardModel.createManagerCard(
        name: '技術顧問',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 95,
        mpAdd: 135,
        pointAdd: 115,
        createAdd: 85,
        popularAdd: 75,
      ),
      CardModel.createMarketerCard(
        name: '創業導師',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 90,
        mpAdd: 130,
        pointAdd: 110,
        createAdd: 80,
        popularAdd: 70,
      ),
      CardModel.createProgrammerCard(
        name: '投資顧問',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 85,
        mpAdd: 125,
        pointAdd: 105,
        createAdd: 75,
        popularAdd: 65,
      ),
      CardModel.createDesignerCard(
        name: '法律顧問',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 80,
        mpAdd: 120,
        pointAdd: 100,
        createAdd: 70,
        popularAdd: 60,
      ),
      CardModel.createManagerCard(
        name: '財務顧問',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 85,
        mpAdd: 125,
        pointAdd: 105,
        createAdd: 75,
        popularAdd: 65,
      ),
      CardModel.createMarketerCard(
        name: '人力資源顧問',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 80,
        mpAdd: 120,
        pointAdd: 100,
        createAdd: 70,
        popularAdd: 60,
      ),
      CardModel.createProgrammerCard(
        name: '國際化專家',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 85,
        mpAdd: 125,
        pointAdd: 105,
        createAdd: 75,
        popularAdd: 65,
      ),
      CardModel.createDesignerCard(
        name: '本地化專家',
        rank: CardRank.SSR,
        connect: 4,
        hpAdd: 80,
        mpAdd: 120,
        pointAdd: 100,
        createAdd: 70,
        popularAdd: 60,
      ),
    ];
  }

  // 獲取所有卡片
  static List<CardModel> getAllCards() {
    return [
      ...createDeveloperCards(),
      ...createDesignerCards(),
      ...createManagerCards(),
      ...createMarketerCards(),
      ...createSpecialCards(),
    ];
  }

  // 獲取初始卡片（新玩家可選擇的三張卡片）
  static List<CardModel> getInitialCards() {
    return [
      createDeveloperCards()[0],  // 前端工程師
      createDesignerCards()[0],   // UI設計師
      createManagerCards()[0],    // 產品經理
    ];
  }
} 